apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-a7nm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0069-tenant/tkrw-pr712-0075-0069-app/devfile-sample-a7nm@sha256:ac0e1782c2ce656541bab17197323d5af7cb885a874086ded8c261a1c954316d
        name: my-nodejs
        resources: {}
status: {}
